### ISSUE TITLE
想找一本日輕，不知道大神有沒有備份到...

### ISSUE THREAD

**Issue by CyanW0202** [ZALin/ESJ-novel-backup#1]
叫「始於賭約的告別之戀」，網上只找到了日文版的。聽說esj上有，但我來的太晚了...

拜託了。

**Comment by Lost-Season** [comment]
[始于赌约的告别之恋.txt](https://github.com/ZALin/ESJ-novel-backup/files/10051152/default.txt)
抓得不是很好，凑合看一下吧

**Comment by ZALin** [comment]
備份的資料都放在 [ESJZone-novel-mirror](https://github.com/ZALin/ESJZone-novel-mirror)

[始于赌约的告别之恋.txt](Novel/日輕/始于赌约的告别之恋.txt)

另外，本作還存在於該網站
